CREATE TABLE IF NOT EXISTS mpa_ratings (
    mpa_rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_rating_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(200) NOT NULL,
    description varchar(200),
    release_date date,
    duration bigint,
    mpa_rating_id int REFERENCES mpa_ratings(mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200) UNIQUE,
    user_login varchar(50) NOT NULL UNIQUE,
    user_name varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS friends (
    user_1_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    user_2_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    friendship_status boolean,
    PRIMARY KEY (user_1_id, user_2_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id bigint NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id int NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id bigint NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);
